# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireFlight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Mapbox-iOS-SDK', '~> 5.2'
pod 'Floaty', '~> 4.2.0'


  target 'FireFlightTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
